### PR TITLE
Add Apns Configs

### PR DESCRIPTION
**Pull request by tacoman667**
RE: Issue #2 

Adding configs for apns push.

### CODE REVIEW

**Comment by tacoman667** [comment]
This is ready for review, me thinks.

**Comment by UTurista** [comment]
It feels odd having two classes with almost identical name - `ApsConfig` and `ApnsConfig`. Specially when `ApsConfig` could be an internal class build with `ApnsPayload.Builder`, just like I do with `Message#Title` and `Message#Body`. 

Nevertheless it won't be because of this Ill reject the PR I just want you to confirm that `ApnsPayload` is indeed correctly implemented.
The [official docs](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/PayloadKeyReference.html#//apple_ref/doc/uid/TP40008194-CH17-SW1) say:
>The payload is a JSON dictionary object(..). The JSON dictionary object must contain an `aps` key, the value of which is a dictionary containing data used by the system to deliver the notification.
(..)In addition to the aps dictionary, the JSON dictionary can include custom keys and values with your app-specific content

You however seem to have created this custom dictionary inside a `data` key, which it seems is not necessary.

-- edit --
As example, for what I understood the serialization of ApnsPayload should something like this:
```
{
    "aps":{ },
    "customKey": "customValue"
}
```
While you have:
```
{
    "aps":{ },
    data:{
        "customKey": "customValue"
    }
}
```

**Comment by tacoman667** [comment]
The reason I created the `Data` collection was more of a consistency between Android and iOS notifications. If someone is using this library, they are more than likely using both platforms and I really wanted to reduce the confusion of a `Payload` being both a dictionary, and a class with properties on it just for `aps` collection. Android has a specific `Data` collection for "extras" and so I just carried that convention over to the iOS side.

It doesn't fail on iOS using that as APNS just sees `data` as a KeyValue pair anyways. So while it is unnecessary, I made that decision for consistency across the "platforms".

**Comment by UTurista** [comment]
Unfortunately, this means that anyone who already has the client part already implemented would may need to change it in order to be compatible with this library, which should never be the case.

This being said, the IOS part is completely to be done and I would probably not give it any attention so soon, as such, this is an appreciated contribution and if you do want to keep this design choice I'll merge it straight away.

**Comment by tacoman667** [comment]
@UTurista I would completely agree if not for the fact that this library hasn't yet reached 1.0 so it's completely understandable, and expected, that there will be breaking changes to the API before it hits that milestone. Also, the previous `ApnsConfig` class was virtually unusable with no way to instantiate the two dictionaries without some hackery so I would think this would be a welcome change to any who had to do it.

For example, the only way I was still able to use it was:
```
class ApnsConfig : UTurista.FCMessaging.ApnsConfig
  {
    [JsonProperty("headers")]
    new public Dictionary<string, string> headers { get; internal set; } = new Dictionary<string, string>();
    [JsonProperty("payload")]
    new public Dictionary<string, object> payload { get; internal set; } = new Dictionary<string, object>();
}
```
and this is a pretty smelly way to bypass a proper solution. The `new` declarations is not all that straight forward for most developers not already experienced with how it works in this instance.

**Pull request merged**
